export const GET_MACHINES = "GET_MACHINES"
export const ADD_MACHINE = "ADD_MACHINE"

export const GET_PROCESSANDSCREEN = "GET_PROCESSANDSCREEN"

export const GET_ERRORS = "GET_ERRORS"
export const CREATE_MESSAGE = "CREATE_MESSAGE"

export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"